

#ifndef CONFIG_H
# define CONFIG_H

#define WINDOW_WIDTH	800
#define WINDOWS_HEIGHT	600

#define FPS				30
#define FRAME_TIME_MS	1000.0/FPS

#define GEN_PER_SECOND	5
#define GEN_DURATION_MS	1000.0/GEN_PER_SECOND

#define CELL_SIZE		10
#define GRID_WIDTH		WINDOW_WIDTH / CELL_SIZE
#define GRID_HEIGHT		WINDOWS_HEIGHT / CELL_SIZE

#endif